### ISSUE TITLE
Ignore /vendor directory

### ISSUE THREAD

**Issue by levakin** [mvdan/gofumpt#136]
When using gofumpt ./... we should have same behaviour as gofmt and ignore /vendor directory. Now gofumpt modifies files inside of vendor.

**Comment by mvdan** [comment]
I think you're confusing `gofmt` with `go fmt`. `gofumpt` is a replacement for the former, not the latter. `gofmt` takes directories or files, and not packages, so it doesn't understand `./...` nor vendor directories.

I know that answer is not helping you come to a solution, but I thought I'd clarify :)

As for an actual solution - there's not really an easy one, because this tool is a fork of `gofmt`, and `gofmt` doesn't attempt to understand packages. That said, `gofumpt` already has some logic to understand what module it's running in (https://github.com/mvdan/gofumpt/issues/67), so I think I could extend that to also ignore a module's vendor directory.
