### ISSUE TITLE
Make ignoring of Go files containing generated code optional

### ISSUE THREAD

**Issue by MarkRosemaker** [mvdan/gofumpt#180]
https://github.com/mvdan/gofumpt/issues/71 and https://github.com/mvdan/gofumpt/pull/150 have presented me with a problem: I have written a tool that autogenerates files and then formats them. 
However, since upgrading my gofumpt version, it doesn't format my autogenerated files unless I employ a hack.

Could we find a way to make ignoring of generated code files optional so the the tool that generated it can format it?

**Comment by mvdan** [comment]
I think this is a very fair request. It's also fair that we swapped the default behavior for `gofumpt -w .`, I think, because otherwise we'd be forcing every generator to follow gofumpt or have to run it afterwards.

So we need some way for you to be able to tell gofumpt "I really do want you to format this file properly, I don't care that it's generated".

My initial thought goes towards making `gofumpt -w generated.go` do that, whereas walking the directory via `gofumpt -w .` would disable the extra rules for that file as it does on the latest release. It's unfortunate to have this silent change of behavior, though we already do something similar for `vendor` folders; they are entirely skipped in `gofumpt -w .`, and only formatted if one explicitly does `gofumpt -w vendor`.

It still feels like too much magic, though. I think I'd be surprised as a user if running `gofumpt -w .` and then `gofumpt -w gen.go` produced changes. At least with `vendor`, the rule is easier to understand and less surprising.

The next thought that comes to mind is a flag, like `-g` or `-generated`, which would get you the old behavior for all the files being formatted. Adding more flags isn't ideal, but perhaps better than hidden magic :) Thoughts?

**Comment by matrixik** [comment]
I think flag is better, e.g. if you have a lot of generated files should you list all of them for gofumpt every time you regenerate them (so more like creating additional script to find all of them and feed to gofumpt)?

**Comment by mmlb** [comment]
I've just come across this issue while trying to update gofumpt for https://github.com/tinkerbell/tink. I'm fine with either way, but actually am already running gofumpt with the files passed in directly (https://github.com/tinkerbell/tink/blob/41bf3415eb244609cb9d35548b16f26f26080efa/rules.mk#L73-L85), this has a little more weight imo as its already being done for `vendor`.

To be fair `vendor` is extra special because its a directory and not a file, maybe `.` is flipped to be the special case where if `.` is passed as the sole argument both generated and vendor files are skipped? I think this is the least surprising method. I find it confusing to pass in a file or directory and be silently ignored ... maybe (depending if the path was `vendor` or not).

If the add an arg/flag route is taken I'd like to see it used to apply to vendor too and do away with `vendor` special case. Maybe `-include` takes a csv, where `-include` == `-include=vendored,generated`. I don't like the flag approach but wanted to throw this one out for completeness.

**Comment by mvdan** [comment]
The above is now implemented; please let me know if it's not working as expected :) I intend to release it as part of v0.3.0 very soon.

**Comment by MarkRosemaker** [comment]
Thank you so much, @mvdan - it works! :)

**Comment by adambabik** [comment]
@mvdan I got an interesting case which was introduced by https://github.com/mvdan/gofumpt/pull/195. 

I use pre-commit and more precisely [pre-commit-golang](https://github.com/TekWizely/pre-commit-golang) which provides gofumpt. gofump is executed with _a list of files_ that have changed and sometimes that list contains auto-generated files. It worked fine before but now with the new rule of formatting explicitly given files the flow is broken.

Overall, I think we won't avoid having a flag that would enable/disable this behaviour globally. From my experience the most popular approaches are (1) don't touch auto-generated files ever, (2) allow formatting generated files with a flag.

IMO (1) makes sense and it's a courtesy of various tools to provide (2) as well. A tool generating a file should be responsible for formatting it.

**Comment by mvdan** [comment]
If pre-commit-golang is taking responsibility of choosing what files need to be fed to gofumpt, I think it needs to then also take care of finding out what files are generated and then decide whether to feed them to gofumpt or not.

The current approach already gives you the choice - the problem was that the previous approach did not give you a choice at all, since generated files were _never_ formatted fully by gofumpt.

**Comment by adambabik** [comment]
pre-commit is a generic tool, it does not look into file's content which is pretty much only reliable way to find if a file is generated. There is a way to circumvent it with `exclude` which excludes listed files, though. 

Yes, it gives me a choice but IMO it's a bit confusing and inflexible. For example, I can run `gofumpt -l -d .` and it will result in no diff. Now, if I'd like to run it only against changed files with `git status --porcelain | sed s/^...// | xargs gofumpt -l -d` it might give me a completely different result because it will inspect generated files.

Not a blocker for me at this point but I wanted to share this use-case.

**Comment by mvdan** [comment]
I understand it's slightly awkward if you assume that running gofumpt on directories and files should behave the same, but that was always the case with vendor directories, and you can use a bit of shell logic to get the behavior you want. For example, you could use `gofumpt -l` to know the set of files that would normally be re-formatted, and intersect that with the set of files changed in VCS.

I personally avoid this situation by not tying the "must be formatted" checks to VCS state: in CI I enforce that all files must be formatted correctly.
