### ISSUE TITLE
Build fails with Go 1.16.x

### ISSUE THREAD

**Issue by ChrisHines** [mvdan/gofumpt#215]
```
$ go1.16.15 install mvdan.cc/gofumpt@latest
//go:build comment without // +build comment
```

I wish the error message included a file and line number so I could more easily investigate the root cause more easily, but alas, it doesn't.

The previous release works, though.

```
$ go1.16.15 install mvdan.cc/gofumpt@v0.3.0
$
```

```
$ git clone https://github.com/mvdan/gofumpt.git
Cloning into 'gofumpt'...
remote: Enumerating objects: 1415, done.
remote: Counting objects: 100% (563/563), done.
remote: Compressing objects: 100% (323/323), done.
remote: Total 1415 (delta 302), reused 345 (delta 168), pack-reused 852
Receiving objects: 100% (1415/1415), 572.24 KiB | 8.54 MiB/s, done.
Resolving deltas: 100% (787/787), done.

$ cd gofumpt/
gofumpt (master=) $ go1.16.15 build
//go:build comment without // +build comment

$ grep "//go:build" *.go
ulimit_unix_test.go://go:build linux

$ head ulimit_unix_test.go
// Copyright (c) 2019, Daniel Martí <mvdan@mvdan.cc>
// See LICENSE for licensing information

// TODO: replace with the unix build tag once we require Go 1.19 or later
//go:build linux

package main

import (
	"bytes"
```

I know you're not officially supporting Go 1.16 anymore and are under no obligation to fix this, but it surprised my team at $work where our project is still using Go 1.16 for the time being.

**Comment by mvdan** [comment]
I can sympathize, because at $work we're also not able to upgrade to Go 1.18 yet due to some tools lagging behind on support. And, arguably, it was wrong of me to release a bugfix that can break some users, even if generally that's okay given the "two Go releases" support.

It's really easy for me to fix this regression, and it wasn't really intentional to break 1.16.x, even if it's no longer supported. I'll push a fix. I'll probably push a tag as well, but I might skip the proper release, because for Go 1.17.x or 1.18.x users there won't be a difference.

By the way, just my 2c: I generally only run tools like gofumpt on the latest Go version, so if you're currently on 1.16.x and 1.17.x, I'd only build and run gofumpt on 1.17.x. That saves CI time, ensures there are no discrepancies (e.g. an older `go/printer` might result in different formatting), and also reduces the chances for incompatibilities like this one. It's perhaps reasonable to also want to run vet or staticcheck on older supported Go versions, for the sake of finding issues in code only built with those older versions, but for build-tag-agnostic tools like gofumpt that isn't a factor at all.

**Comment by mvdan** [comment]
Fix pushed to master. I'd like to avoid the tag/release noise if possible, so let me know if the workaround above (not using gofumpt on 1.16.x) or using master is enough for now.

**Comment by ChrisHines** [comment]
Thanks. I think it will be fine. We initially encountered the error because the script that builds our CI base image included `go install mvdan.cc/gofumpt@latest`. We don't need `gofumpt` in that image, though, so we took it out.

We do ask our developers to use `gofumpt` in their workflow. If anyone gets this error I'll know how to get them past it without a new `gofumpt` release right now.

Also, thanks for `gofumpt` I heartily 👍 it's additional rules.

**Comment by mvdan** [comment]
Sounds good, thanks again for reporting :)
