### ISSUE TITLE
Add formatting based on WSL rules. 

### ISSUE THREAD

**Issue by anderson-lt** [mvdan/gofumpt#242]
Add formatting based on WSL rules: https://github.com/bombsimon/wsl

This linter tries to make the code more readable, simply by trying to add line breaks in certain places.

I have personally tried the linter and found its suggestions helpful, but it would be helpful if GoFumpt applied them automatically.

**Comment by mvdan** [comment]
For breaking up long lines with newlines, see https://github.com/mvdan/gofumpt/issues/2.

We already have some of our own whitespace rules, such as this one in the README:

> Multiline top-level declarations must be separated by empty lines

If you think we should add any other rule _in particular_, please open an issue and we can evaluate it. I do not plan on simply copying or bundling another linter as part of gofumpt, because others tend to have a different design when compared to gofumpt. wsl in particular seems to be a lot more aggressive: it found dozens of warnings on this repository, and a quick skim of some of them makes me think that they aren't appropriate for gofumpt.

It's fine for some users to prefer lots of empty lines, and they can use wsl. The purpose of gofumpt is to be much closer to gofmt, so it aims to be more conservative than that.
