### ISSUE TITLE
create official releases?

### ISSUE THREAD

**Issue by twpayne** [mvdan/gofumpt#28]
`gofumpt` is excellent, I'm using in my personal projects, and introducing it at work. I'd like to add CI checks to ensure that all code is formatted with `gofumpt`. This requires defining a version of `gofumpt` to use.

At the moment, there are no official releases of `gofumpt`, e.g. there are no tagged versions.

Would you consider a PR that adds a configuration for [`goreleaser`](https://goreleaser.com/)? This would mean that when you push a tag to GitHub you get tarballs, packages, install scripts, etc. built automatically and uploaded to GitHub. `goreleaser` is working extremely well for me in my [`chezmoi`](https://github.com/twpayne/chezmoi) project, and I'd be happy to pay @joemiller's [contribution](https://github.com/twpayne/chezmoi/pull/33) forward.

**Comment by mvdan** [comment]
This issue covers multiple topics. The first is tagged versions; are these really necessary? With Go modules, you can easily pin to a v0 pseudo-version. For example, the command below pins to the latest commit from master:

    go get mvdan.cc/gofumpt@v0.0.0-20190629185957-5c4608766f49

You can figure out what the latest pseudo-version is with a command like `go get -json mvdan.cc/gofumpt`. You can also use `go list -f '{{.Module.Version}}' mvdan.cc/gofumpt`, which will directly print the version string alone.

The second bit of the issue is about fancy releases with tarballs and all the extras. I expect any gofumpt user to also have Go installed, so I think a `go get` command is the right way to install the tool. I've also reasoned above that I don't think semver releases are necessary at this point, so I'm not sure that there's anything I should do here.

**Comment by twpayne** [comment]
An advantage of a fancy release with tarballs is that you get a pre-built binary which is much faster to install than downloading all the source code and rebuilding from zero. It's also more robust as you only need GitHub to be up, not all the infrastructure required to download everything in `gofumpt`'s dependency graph. See [`golangci-lint`'s install instructions](https://github.com/golangci/golangci-lint/blob/master/README.md#install) for an example.

**Comment by mvdan** [comment]
With proxy.golang.org being live, it can be relied on for "robust" downloads :)

A build from zero should also take mere seconds on most machines, so I'm not sure if we're solving a real problem.

As a side point - the install instructions you link to follow a `curl ... | sh` pattern, which I don't think should be recommended. `go get ...` can't run arbitrary code, at least.

I appreciate your input here, by the way - I'm just not convinced that all this extra machinery makes sense for small projects. Particularly those which are Go tools, where the users are developers well familiar with `go get`.

**Comment by mvdan** [comment]
I think this is a bit overkill right now. If the Go proxy and module version pinning don't work, please let me know and we can consider reopening. Thanks!
