### ISSUE TITLE
remove empty declarations

### ISSUE THREAD

**Issue by twpayne** [mvdan/gofumpt#49]
Currently `gofumpt` leaves empty declarations like

```go
const ()

type ()

var ()
```

unchanged. Perhaps they should be removed?

**Comment by mvdan** [comment]
I agree with you, though I wonder if this would be too agressive. None of the current rules entirely remove a piece of code; we only manage whitespace, ordering, or single tokens within nodes. I don't think we entirely remove a whole declaration or statement in any scenario.

The reason I don't want to be agressive is so that we don't discourage the use of the tool while developing. Maybe someone opens a `var ()` to add some variables and hits save before actually adding the variables. It could be annoying for the tool to fight you on this.

Having said all this, it's still probably worth a try, and see if any users complain. After all, Go is already pretty unfriendly to unfinished code, such as its errors on "defined but not used".

**Comment by twpayne** [comment]
> Maybe someone opens a `var ()` to add some variables and hits save before actually adding the variables.

FWIW, I hit upon this from the opposite side. I had an existing `var` block, deleted all the variables in it, and was surprised to see that this got reformatted to `var ()` rather than removing the block entirely.

**Comment by kovetskiy** [comment]
```
The reason I don't want to be agressive is so that we don't discourage the use of the tool while developing. Maybe someone opens a var () to add some variables and hits save before actually adding the variables. It could be annoying for the tool to fight you on this.
```

That's actually quite a huge argument, I often see such behavior in Java code formatters (they remove newline+tab in empty functions) and it's very frustrating.

**Comment by mvdan** [comment]
@kovetskiy gofmt would already do that kind of thing already, though. I guess it depends on what your IDE runs to continuously format your code, and whether you hit save on unfinished code.

I think, given that gofmt doesn't work well with unfinished code, people aren't running it with yet-to-be-filled var blocks or functions. So I think it should be safe to add a rule like this one. But I'm happy to be proven wrong if people complain, or if others show proof that editors are indeed running gofmt continuously, even on unfinished code.

**Comment by mvdan** [comment]
I think I've convinced myself that adding this rule is a good idea - as long as there aren't any comments between the parentheses, like:

```
var (
    // foo = bar
)
```
