### ISSUE TITLE
weird installation instructions

### ISSUE THREAD

**Issue by josharian** [mvdan/gofumpt#5]
I don't recall a Go README ever suggesting mktemp or 'go mod init'. Why?

**Comment by mvdan** [comment]
:) As of Go 1.11 and 1.12, it's the only way to reliably install the tool in module mode without modifying the current `go.mod`. If https://github.com/golang/go/issues/30515 was done, we could replace that entire line with something like `go get -global mvdan.cc/gofumpt`.

I understand I could suggest `go get mvdan.cc/gofumpt` and add a warning about running this outside a module, but I think that will still confuse some users who aren't used to modules. The longer line can be copy-pasted in all scenarios, and the expert Go users can do their own thing anyway.

**Comment by josharian** [comment]
Yuck. Seems like we definitely need something like golang/go#30515. What I ended up doing was cloning and then running go install.

I'm not an expert Go user (when it comes to modules). I wonder whether `git clone ...; cd gofumpt; go install` would be more comprehensible to most folks on first pass?

**Comment by mvdan** [comment]
Yes, a clone is the other option. The disadvantage being that it gets `@master`, not `@latest` (which is different if there are tagged releases), and it might not use module mode if `$PWD` happens to be inside `$GOPATH`.

And of course, it also pollutes `$PWD`. I think polluting `/tmp` or whichever other temporary directory is a bit less harmful.

Either way it's going to be multiple commands and ugly; this is just one way that I've found does what I want, works for all projects, and is usable on all Go releases since 1.11. So I'll probably be using it for a while.

**Comment by rodrigc** [comment]
@mvdan take a look at https://github.com/golang/go/issues/30515#issuecomment-480543097 and see if that approach works for you.  That is one suggestion that is being discussed.

**Comment by mvdan** [comment]
Yes, I am aware of that thread; I started it. That's not the right approach I'm afraid, as someone already pointed out there.
