### ISSUE TITLE
ignore Go files containing generated code

### ISSUE THREAD

**Issue by rhzs** [mvdan/gofumpt#71]
Hi,

I have use cases where i need to ignore specific files / directories. How can I achieve that? Is there any example?

**Comment by mvdan** [comment]
neither `gofmt` nor `go fmt` have any way to skip generated files, so I've gone the same route for now. The typical answer is that your generated code should be properly formatted too. You can achieve this by either modifying the generator to directly produce well-formatted code, or by running the formatter after it, like:

```
//go:generate some-generator -out gen.go
//go:generate gofumpt -w gen.go
```

However, I'm having second thoughts given the proposed feature to split long lines in #2. Long lines in a generated file aren't necessarily a bad thing, especially when generated files are bundling binary data or assets.

One possible solution here is to skip any file that has the magic `Code generated by` comment near the top. However, that could be counter-intuitive; running `gofumpt -w gen.go` might not do anything just because that file has that special comment. Perhaps we can add this restriction only when formatting entire directories.

**Comment by mvdan** [comment]
New idea: no matter how we came to format a file (stdin, explicit arg, or directory walking), if it has a "Code generated by" comment near the top, we turn off some of the rules. "split long lines" is perhaps the most obvious, since many code generators like stringer will output large tables and strings which don't need to be human-readable or editable.

Another option would be to go ahead and disable all gofumpt rules for generated files, just running the basic gofmt formatting.
