### ISSUE TITLE
VSCode settings not recognized

### ISSUE THREAD

**Issue by macintacos** [mvdan/gofumpt#83]
Tried setting this up in VSCode as it says in the wiki, it says that the properties used are not allowed:

![image](https://user-images.githubusercontent.com/8128941/90696519-66e59280-e24a-11ea-8204-e3b0708e699b.png)

Any ways around this?

**Comment by gonzaloserrano** [comment]
Hey, so the people from my team that use VSCode also have the same prob and have not been able to fix it yet :-(

**Comment by xabinapal** [comment]
Just found a workaround. Instead of specifying the alternate tool for `goimports`, it should be set as the **default** tool with `"go.formatTool": "gofumpt"` or `"go.formatTool": "gofumports"`.

VS Code will then complain about some not accepted value bullshit. Just ignore it, it works nicely. If you save a Go file, you will notice that the `gofumpt` extra rules are applied.

The language server **must be disabled**, as formatting is not applied when enabled. I couldn't find a workaround for this, the `go.languageServerExperimentalFeature` property does not work. 

Not sure why the VSCode team thought it was a good idea to pseudo-restrict the valid formatters to only four options, but this requirement is not enforced.

**Comment by mvdan** [comment]
I should also note that gofumpt is now supported as part of gopls; so I think we should generally recommend that instead of disabling gopls entirely. See https://github.com/golang/go/issues/39805.

@xabinapal could you please amend your PR to explain how to use gofumpt with or without gopls?

**Comment by xabinapal** [comment]
Did not know that it was supported, nice!

Let me discover how to configure gopls and I'll update my PR.

**Comment by xabinapal** [comment]
Just an update about this. The extension has just been updated and in the last release v0.16.2, they have fixed the warnings of the `go.alternateTools` setting. Also, there is a pending patch to recognize both `gofumpt` and `goimports` as native formatters of the `go.formatTool` setting: https://go-review.googlesource.com/c/vscode-go/+/252922/1

@mvdan when that patch is merged I'll update my PR again to reflect those additions. The last commit I made with the language server configuration doesn't change and works as expected.

**Comment by mvdan** [comment]
OK cool, I'll wait for you to update the PR, then :)

**Comment by bitfield** [comment]
Just FYI, to enable `gofumpt`age with the current VS Code/gopls, add this to your `settings.json`:

```json
    "gopls": {
        "gofumpt": true,
    },
```

**Comment by Zamiell** [comment]
Thanks so much xabinapal. Your above instructions worked perfectly. <3

**Comment by macintacos** [comment]
Sorry, I don't understand how this is supposed to work. `gopls` is coming up as an unknown configuration setting for me, see: https://github.com/golang/vscode-go/issues/556. They closed it in favor of https://github.com/golang/vscode-go/issues/197, but nevertheless it doesn't work at all for me.

Are folks here using the nightly version of the Go plugin or something? I don't want to switch to a version that is not stable to get this working if I can help it.

**Comment by xabinapal** [comment]
macintacos it shows as an unknown setting but it's recognized. This is a known issue because `gopls` settings are not yet standardized, and because of this reason, the haven't been included as known properties in the VS Code extension.
