### ISSUE TITLE
Move gofumports out of vanity domain?

### ISSUE THREAD

**Issue by flowchartsman** [mvdan/gofumpt#9]
It would be nice to be able to build gofumports out of the github repo, unless there's a particularly compelling reason to keep it on mvdan.cc

```
github.com/mvdan/gofumpt/gofumports$ go install
goimports.go:25:2: cannot find package "mvdan.cc/gofumpt/internal" in any of:
        /Users/awalker/opt/go/src/mvdan.cc/gofumpt/internal (from $GOROOT)
        /Users/awalker/opsgo/src/mvdan.cc/gofumpt/internal (from $GOPATH)
```

**Comment by mvdan** [comment]
Please clarify why you'd like to build this with the github import paths. A Go package must only have one import path, so I can't offer building with both.

The reason to keep it away from github.com is simple; I control the domain, so if I ever want to move to another git repository, I can do so with minimal effort and without breaking users.

You may argue that github is here to stay, but history says otherwise (sourceforge, google code).

**Comment by flowchartsman** [comment]
Thats fair. It was merely for convenience if you didn't feel strongly about it. Since you do, and since we haven't yet rallied around a canonical package repository I see no reason to have any problem with your choice. Feel free to close.
