### ISSUE TITLE
gofumpt should use tagging and version numbers

### ISSUE THREAD

**Issue by Zamiell** [mvdan/gofumpt#99]
Hello again,

In general, it is nice for software to have version numbers, and `gofumpt` is no exception.

Having versioning is particularly important because according to [this comment](https://github.com/golangci/golangci-lint/issues/1547#issuecomment-742770106), `gofumpt` would automatically be updated inside `golangci-lint` if it used version tags.

For example, by looking at [the commit history for golangci-lint](https://github.com/golangci/golangci-lint/commits/master), we can see that one of the latest commits is an automatic commit by [Dependabot](https://dependabot.com/) for the `gci` linter. This is because the `gci` linter [uses git tags, which are listed here](https://github.com/daixiang0/gci/tags).

It would be nice if `gofumpt` would follow the same conventions that `gci` and other linters do, so that `golangci-lint` would be automatically updated. Even if you don't want to package up a proper release with a zip file or whatnot, it is my understanding that by simply tagging the latest commit on master with a version number, it will get the job done.

Thanks again for the tool.

**Comment by mvdan** [comment]
I have to say - it feels rather arbitrary that golangci-lint requires tags to automatically update. They could just as easily have a weekly or daily cron job that does a `go get some-tool@latest` and it would work just fine with tools which don't use tags.

That said, I have been thinking about using tags for a couple of months, simply because the project has grown in popularity and it makes stable usage and packaging easier.

**Comment by mvdan** [comment]
First release is out: https://github.com/mvdan/gofumpt/releases/tag/v0.1.0

**Comment by Zamiell** [comment]
Thanks Dan.
